### ISSUE TITLE
NoSuchFieldError: AIR

### ISSUE THREAD

**Issue by Flimsy-Fox** [jaquadro/Chameleon#6]
Minecraft crashes during loading when Chameleon is installed. Game does not crash when Chameleon is disabled.
Here's the stacktrace:
`java.lang.NoSuchFieldError: AIR
    at com.jaquadro.minecraft.chameleon.resources.ModelRegistry.loadModels(ModelRegistry.java:95)
    at com.jaquadro.minecraft.chameleon.core.ClientProxy.onModelBakeEvent(ClientProxy.java:33)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1256_ClientProxy_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
    at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:30)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.init(Minecraft.java:513)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)`

[Full log here](https://mclo.gs/RtV9hYI)

**Comment by juraj-hrivnak** [comment]
Can confirm this error. Here is my [latest.log](https://gist.github.com/juraj-hrivnak/0752db653b9460abc994e136dd932b78).
It is also happening for me only with the version from Modrinth: [Chameleon 1.12.2-4.1.3](https://modrinth.com/mod/texel-chameleon/version/4.1.3).
